# Generated by Django 2.1.7 on 2019-02-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiWooc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
