# Generated by Django 2.1.7 on 2019-02-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiWooc', '0002_parcel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='woocUser',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
